/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "ab_jobqueue.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef AB_JOBQUEUE_H
#define AB_JOBQUEUE_H


#ifdef __cplusplus
extern "C" {
#endif

/* needed system headers */
#include <gwenhywfar/types.h>
#include <gwenhywfar/list1.h>
#include <gwenhywfar/inherit.h>

/* pre-headers */
#include <aqbanking/job.h>

typedef struct AB_JOBQUEUE AB_JOBQUEUE;
GWEN_LIST_FUNCTION_LIB_DEFS(AB_JOBQUEUE, AB_JobQueue, AQBANKING_API)
GWEN_INHERIT_FUNCTION_LIB_DEFS(AB_JOBQUEUE, AQBANKING_API)


/* post-headers */


/** Constructor. */
AQBANKING_API AB_JOBQUEUE *AB_JobQueue_new();

/** Destructor. */
AQBANKING_API void AB_JobQueue_free(AB_JOBQUEUE *p_struct);

AQBANKING_API void AB_JobQueue_Attach(AB_JOBQUEUE *p_struct);

AQBANKING_API AB_JOBQUEUE *AB_JobQueue_dup(const AB_JOBQUEUE *p_struct);

/** Getter.
 * Use this function to get the member "jobList"
*/
AQBANKING_API AB_JOB_LIST2 *AB_JobQueue_GetJobList(const AB_JOBQUEUE *p_struct);

/** Getter.
 * Use this function to get the member "jobType"
*/
AQBANKING_API int AB_JobQueue_GetJobType(const AB_JOBQUEUE *p_struct);

/** Setter.
 * Use this function to set the member "jobList"
*/
AQBANKING_API void AB_JobQueue_SetJobList(AB_JOBQUEUE *p_struct, AB_JOB_LIST2 *p_src);

/** Setter.
 * Use this function to set the member "jobType"
*/
AQBANKING_API void AB_JobQueue_SetJobType(AB_JOBQUEUE *p_struct, int p_src);

AQBANKING_API AB_JOBQUEUE_LIST *AB_JobQueue_List_dup(const AB_JOBQUEUE_LIST *p_src);

#ifdef __cplusplus
}
#endif

#endif

