/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "ab_queue.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef AB_QUEUE_H
#define AB_QUEUE_H


#ifdef __cplusplus
extern "C" {
#endif

/* needed system headers */
#include <gwenhywfar/types.h>
#include <gwenhywfar/inherit.h>

/* pre-headers */
#include <aqbanking/banking.h>
#include <aqbanking/ab_userqueue.h>

typedef struct AB_QUEUE AB_QUEUE;
GWEN_INHERIT_FUNCTION_LIB_DEFS(AB_QUEUE, AQBANKING_API)


/* post-headers */
#include <aqbanking/ab_queuefns.h>


/** Constructor. */
AQBANKING_API AB_QUEUE *AB_Queue_new();

/** Destructor. */
AQBANKING_API void AB_Queue_free(AB_QUEUE *p_struct);

AQBANKING_API void AB_Queue_Attach(AB_QUEUE *p_struct);

AQBANKING_API AB_QUEUE *AB_Queue_dup(const AB_QUEUE *p_struct);

/** Getter.
 * Use this function to get the member "userQueueList"
*/
AQBANKING_API AB_USERQUEUE_LIST *AB_Queue_GetUserQueueList(const AB_QUEUE *p_struct);

/** Setter.
 * Use this function to set the member "userQueueList"
*/
AQBANKING_API void AB_Queue_SetUserQueueList(AB_QUEUE *p_struct, AB_USERQUEUE_LIST *p_src);

#ifdef __cplusplus
}
#endif

#endif

